spring.application.name=chat-app-backend

    spring.data.mongodb.uri=mongodb://JavaChat:azhan123@ac-fm0wtuz-shard-00-00.pbqwgkc.mongodb.net:27017,ac-fm0wtuz-shard-00-01.pbqwgkc.mongodb.net:27017,ac-fm0wtuz-shard-00-02.pbqwgkc.mongodb.net:27017/?ssl=true&replicaSet=atlas-mc6fmx-shard-0&authSource=admin&appName=javaChat
